#---
#apiVersion: networking.istio.io/v1alpha3
#kind: VirtualService
#metadata:
#  name: grpc-downstream-service
#spec:
#  hosts:
#  - downstream.default.svc.cluster.local
#  gateways:
#  - ingress-gateway
#  http:
#  - match:
#    - uri:
#        prefix: "/dev.cognizant_ai.downstream.Service/"
#    route:
#    - destination:
#        host: downstream.default.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: downstream
  labels:
    app: downstream
spec:
  ports:
  - port: 30001
    name: grpc-downstream
  selector:
    app: downstream
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: downstream-v1
  labels:
    version: v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: downstream
        version: v1
    spec:
      containers:
      - name: downstream
        {{if .duat.awsecr}}
        image: {{.duat.awsecr}}/platform-services/{{.duat.module}}:{{.duat.version}}
        {{else}}
        image: localhost:32000/platform-services/{{.duat.module}}:{{.duat.version}}
        {{end}}
        imagePullPolicy: Always
        ports:
        - containerPort: 30001
          name: grpc-downstream
        env:
        - name: "LOGXI_FORMAT"
          value: "happy,maxcol=1024"
        - name: "LOGXI"
          value: "*=TRC"
        - name: "IP_PORT"
          value: ":30001,0.0.0.0:30001"
      resources:
        requests:
          memory: "256Mi"
          cpu: "100m"
        limits:
          memory: "512Mi"
          cpu: "100m"
---
