apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test-eks
  region: us-west-2
  version: '1.19'
  tags:
    # Add more cloud tags if needed for billing
    environment: test-eks

availabilityZones: ["us-west-2a", "us-west-2b",  "us-west-2d"]

cloudWatch:
    clusterLogging:
        # enable specific types of cluster control plane logs
        enableTypes: ["audit", "authenticator", "controllerManager"]
        # all supported types: "api", "audit", "authenticator", "controllerManager", "scheduler"
        # supported special values: "*" and "all"

nodeGroups:
  - name: overhead
    ssh: # import public key from file
      publicKeyPath: ~/.ssh/id_rsa.pub
      allow: true
    minSize: 1
    maxSize: 4
    instanceType: t3.xlarge
    availabilityZones: ["us-west-2a", "us-west-2b",  "us-west-2d"]
    labels:
      node-class: "worker-node"
    tags:
      # EC2 tags required for cluster-autoscaler auto-discovery
      k8s.io/cluster-autoscaler/node-template/label/lifecycle: OnDemand
      k8s.io/cluster-autoscaler/node-template/label/aws.amazon.com/spot: "false"
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/test-eks: "owned"
    iam:
      withAddonPolicies:
        albIngress: true
        autoScaler: true
        cloudWatch: true

#gitops:
#  flux:
#    gitProvider: github             # required. options are github or gitlab
#    owner: karlmutch                # required
#    repository: cluster-gitops      # required
#    personal: true                  # optional. if left false, assumes 'owner' is an org
#    branch: main                    # optional
#    namespace: "gitops-system"      # optional
#    path: "clusters/test-eks"       # optional
