apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-exp
  annotations:
    kubernetes.io/ingress.class: istio
spec:
  rules:
  - http:
      paths:
      - path: /.*
        backend:
          serviceName: experiments
          servicePort: grpc-exp
---
apiVersion: v1
kind: Service
metadata:
  name: experiments
  labels:
    app: experiments
spec:
  ports:
  - port: 30001
    name: grpc-exp
  selector:
    app: experiments
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: experiments-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: experiments
        version: v1
    spec:
      containers:
      - name: experiments
        image: 353515307211.dkr.ecr.us-west-2.amazonaws.com/experimentsrv
        imagePullPolicy: Always
        ports:
        - containerPort: 30001
          name: grpc-exp
        env:
        - name: "LOGXI_FORMAT"
          value: "happy,maxcol=1024"
        - name: "IP_PORT"
          value: ":30001,0.0.0.0:30001"
        - name: "LOGXI"
          value: "*=TRC"
        - name: "PGHOST"
          value: "dev-platform.cluster-cff2uhtd2jzh.us-west-2.rds.amazonaws.com"
        - name: "PGPORT"
          value: "5432"
        - name: "PGDATABASE"
          value: "platform"
        - name: "PGUSER"
          valueFrom:
            secretKeyRef:
              name: postgres
              key: username
        - name: "PGPASSWORD"
          valueFrom:
            secretKeyRef:
              name: postgres
              key: password
---
apiVersion: config.istio.io/v1alpha2
kind: EgressRule
metadata:
  name: auth0-egress-rule
spec:
  destination:
    service: sentientai.auth0.com
  ports:
    - port: 443
      protocol: https
