# The ingress block is used to route requests using path prefix strings.  The downstream
# example uses the protoc file package name and then followed by the name of the service
# from the same protoc file with a dot seperator, a gRPC standard.  The trailing /.* is Istio 
# version specific to 0.7.1 and is being changed on a regular basis, it indicated prefix based
# matching but will change in the future ot using a Gateway approach, please read
# https://istio.io/docs/tasks/traffic-management/ingress.html
#
# The empty prefix is used to allow the default route to the experiment service
# so that reflection, and health checking is defaulted to it.
#
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-exp
  annotations:
    kubernetes.io/ingress.class: istio
spec:
  rules:
  - http:
      paths:
      - path: /ai.sentient.downstream.Service/.*
        backend:
          serviceName: downstream
          servicePort: grpc-downstream
      - path: /.*
        backend:
          serviceName: experiments
          servicePort: grpc-exp
---
apiVersion: v1
kind: Service
metadata:
  name: experiments
  labels:
    app: experiments
spec:
  ports:
  - port: 30001
    name: grpc-exp
  selector:
    app: experiments
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: experiments-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: experiments
        version: v1
    spec:
      containers:
      - name: experiments
        image: {{.duat.awsecr}}/{{.duat.module}}:{{.duat.version}}
        imagePullPolicy: Always
        resources:
          requests:
            memory: "2048Mi"
            cpu: "1"
          limits:
            memory: "2048Mi"
            cpu: "1"
        ports:
        - containerPort: 30001
          name: grpc-exp
        env:
        - name: "LOGXI_FORMAT"
          value: "happy,maxcol=1024"
        - name: "LOGXI"
          value: "*=TRC"
        - name: "IP_PORT"
          value: ":30001,0.0.0.0:30001"
        - name: "PGHOST"
          valueFrom:
            secretKeyRef:
              name: postgres
              key: host
        - name: "PGPORT"
          valueFrom:
            secretKeyRef:
              name: postgres
              key: port
        - name: "PGDATABASE"
          valueFrom:
            secretKeyRef:
              name: postgres
              key: database
        - name: "PGUSER"
          valueFrom:
            secretKeyRef:
              name: postgres
              key: username
        - name: "PGPASSWORD"
          valueFrom:
            secretKeyRef:
              name: postgres
              key: password
---
apiVersion: config.istio.io/v1alpha2
kind: EgressRule
metadata:
  name: auth0-egress
spec:
  destination:
    service: 54.149.162.63/27
  ports:
    - port: 443
      protocol: tcp
---
apiVersion: config.istio.io/v1alpha2
kind: EgressRule
metadata:
  name: rds-egress
spec:
  destination:
    service: 52.42.136.165/27
  ports:
    - port: 5432
      protocol: tcp

