---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres
type: Opaque
data:
  host: '{{ expandenv "$PGHOST" | b64enc }}'
  username: '{{ expandenv "$PGUSER" | b64enc }}'
  password: '{{ expandenv "$PGPASSWORD" | b64enc }}'
  port: '{{ expandenv "$PGPORT" | b64enc }}'
  database: '{{ expandenv "$PGDATABASE" | b64enc }}'
---
apiVersion: v1
kind: Secret
metadata:
  name: honeycomb-key
  namespace: default
type: Opaque
data:
  key: '{{ expandenv "$O11Y_KEY" | b64enc }}'
  apikey: '{{ expandenv "$O11Y_KEY" | b64enc }}'
  dataset: '{{ expandenv "$O11Y_DATASET" | b64enc }}'
