apiVersion: v1
kind: Secret
metadata:
  name: postgres
type: Opaque
data:
  host: '{{ expandenv "$PGHOST" | b64enc }}'
  username: cG9zdGdyZXM=
  password: cDM1NXcwcmQ=
  port: NTQzMg==
  database: cGxhdGZvcm0=

