apiVersion: v1
kind: Secret
metadata:
  name: postgres
type: Opaque
data:
  username: cGw=
  password: cGFzc3dvcmQ=
  host: ZGV2LXBsYXRmb3JtLmNsdXN0ZXItY2ZmMnVodGQyanpoLnVzLXdlc3QtMi5yZHMuYW1hem9uYXdzLmNvbQ==
  port: NTQzMg==
  database: cGxhdGZvcm0=
