apiVersion: v1
kind: Secret
metadata:
  name: postgres
type: Opaque
data:
  host: '{{ expandenv "$PGHOST" | b64enc }}'
  username: cGw=
  password: cGFzc3dvcmQ=
  port: NTQzMg==
  database: cGxhdGZvcm0=

