---
swagger: '2.0'
info:
  version: 1.0.0
  title: Time Server
produces:
  - application/json
schemes:
  - http
paths:
  /time:
    get:
      produces:
        - application/json
      parameters:
        - name: timezone
          required: false
          type: string
          in: query
          description: defaults to UTC if not gievm
      operationId: getTime
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/time"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
definitions:
  time:
    type: object
    properties:
      timestamp:
        type: string
        format: date-time
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
